name: Build and Load

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install libboost-system-dev

      - name: Install jank
        run: |
          curl -s "https://jank-lang.github.io/ppa/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/jank.gpg >/dev/null
          sudo curl -s -o /etc/apt/sources.list.d/jank.list "https://jank-lang.github.io/ppa/jank.list"
          sudo apt update
          sudo apt install -y jank

      - name: Build library
        run: |
          cmake -Bbuild
          cmake --build build

      - name: Load jank code
        run: |
          echo "(require 'nrepl-server.core)" | jank -Isrc/cpp/ -Lbuild/ -lnrepl_server -L/usr/lib/x86_64-linux-gnu/ repl --module-path src/jank/
